export const portfolioData = {
    profile: {
        name: "Alex Cameron",
        role: "Senior Full-Stack Developer & UI Designer",
        bio: "I build websites that are fast, beautiful, and easy for everyone to use.",
        longDescription: "With 3 years of experience in web development, I focus on creating high-quality websites that solve real problems. I make sure every project is built well, looks modern, and provides a smooth experience for every user. My goal is to turn your ideas into a powerful digital reality without making it complicated.",
        mission: "To build simple, powerful, and beautiful websites that make a difference.",
        values: [
            "Creative Thinking",
            "Solid Quality",
            "Modern Design",
            "Fast & Reliable",
            "Clear Communication",
        ],
        avatar: "/images/avatar.jpg",
        email: "alex@muhyo.tech",
        phone: "+1 (555) 000-1234",
        location: "San Francisco, CA",
        socials: {
            github: "https://github.com",
            linkedin: "https://linkedin.com",
            twitter: "https://twitter.com",
        },
    },
    skills: [
        { name: "React / Next.js", level: 95, category: "Frontend" },
        { name: "Tailwind CSS", level: 90, category: "Frontend" },
        { name: "Node.js / Express", level: 85, category: "Backend" },
        { name: "TypeScript", level: 88, category: "Languages" },
        { name: "MongoDB", level: 80, category: "Database" },
        { name: "PostgreSQL", level: 82, category: "Database" },
        { name: "Framer Motion", level: 85, category: "Animation" },
        { name: "GraphQL", level: 75, category: "API" },
    ],
    services: [{
            id: 1,
            slug: "web-development",
            title: "Performance-First Web Development",
            description: "We engineer high-performance, SEO-optimized digital experiences using cutting-edge technologies like Next.js and React. Our websites aren't just pretty—they're built to convert and scale.",
            problemSolved: "Converting casual visitors into loyal customers through lightning-fast load times and intuitive user journeys that drive business growth.",
            benefits: [
                "Blazing Fast Core Web Vitals",
                "Advanced SEO Architecture",
                "Mobile-First Responsive Design",
                "Scalable Cloud-Native Infrastructure",
            ],
            process: [{
                    title: "Strategy & Discovery",
                    description: "Deep dive into your business goals, target audience, and competition to map out a clear digital strategy.",
                },
                {
                    title: "Technical Architecture",
                    description: "Planning the stack, database schema, and API integrations for a robust, future-proof system.",
                },
                {
                    title: "Agile Development",
                    description: "Iterative building with clean, maintainable code and regular progress updates.",
                },
                {
                    title: "Testing & Launch",
                    description: "Rigorous performance, security, and cross-browser testing before the final deployment.",
                },
            ],
            features: [
                "Server-Side Rendering (SSR) & Static Site Generation (SSG)",
                "Custom CMS Integration (Sanity, Contentful, or Strapi)",
                "E-commerce & Dynamic Payment Gateways",
                "Real-time Data & WebSockets Support",
                "Progressive Web App (PWA) Capabilities",
            ],
            techStack: [
                "React",
                "Next.js",
                "TypeScript",
                "Node.js",
                "Tailwind CSS",
                "MongoDB/PostgreSQL",
                "Framer Motion",
            ],
            faq: [{
                    question: "How long does a typical project take?",
                    answer: "A standard web project usually takes 4-8 weeks depending on complexity.",
                },
                {
                    question: "Do you provide post-launch support?",
                    answer: "Yes, we offer monthly maintenance and support packages to keep your site updated and secure.",
                },
            ],
        },
        {
            id: 2,
            slug: "ui-ux-design",
            title: "User-Centric UI/UX Design",
            description: "Transforming complex requirements into simple, elegant, and intuitive user interfaces. We focus on strategic design that aligns with user behavior and business objectives.",
            problemSolved: "Eliminating user frustration and high bounce rates by creating seamless, engaging experiences that keep users coming back.",
            benefits: [
                "Intuitive User Workflows",
                "Consistent Design Systems",
                "Accessible & Inclusive Design",
                "High-Fidelity Prototyping",
            ],
            process: [{
                    title: "User Research",
                    description: "Understanding user personas, pain points, and behavioral patterns through data and interviews.",
                },
                {
                    title: "Wireframing",
                    description: "Creating low-fidelity blueprints to establish layout and information hierarchy.",
                },
                {
                    title: "Visual Design",
                    description: "Crafting beautiful, brand-aligned interfaces with a focus on typography and color theory.",
                },
                {
                    title: "Interaction Design",
                    description: "Adding motion and micro-interactions to breathe life into the final design.",
                },
            ],
            features: [
                "Custom Vector Illustrations & Icons",
                "Interactive High-Fidelity Prototypes",
                "Comprehensive Responsive Design Systems",
                "A/B Testing & Usability Research",
                "Dark Mode & Multi-Theme Support",
            ],
            techStack: [
                "Figma",
                "Adobe Creative Suite",
                "Framer",
                "Spline (3D)",
                "Principle",
            ],
            faq: [{
                    question: "Can you redesign my existing website?",
                    answer: "Absolutely! We specialize in revamping outdated interfaces to modern, high-converting designs.",
                },
                {
                    question: "Do you provide the design files?",
                    answer: "Yes, you will receive full access to all design assets, including Figma files and exported assets.",
                },
            ],
        },
        {
            id: 3,
            slug: "api-development",
            title: "Scalable API & Backend Systems",
            description: "Architecting the invisible engine that powers your business. We build secure, robust, and lightning-fast APIs that handle complex logic and large data volumes with ease.",
            problemSolved: "Streamlining operations and data management through automated, reliable backend systems that eliminate manual errors.",
            benefits: [
                "Military-Grade Security",
                "High Availability Arch",
                "RESTful & GraphQL Support",
                "Easy 3rd-Party Integrations",
            ],
            process: [{
                    title: "Data Modeling",
                    description: "Designing efficient database schemas and relationships to optimize data retrieval.",
                },
                {
                    title: "API Design",
                    description: "Defining clean, documented endpoints using industry standards like OpenAPI/Swagger.",
                },
                {
                    title: "Security Implementation",
                    description: "Integrating JWT, OAuth, and advanced encryption to protect your sensitive data.",
                },
                {
                    title: "Deployment & Monitoring",
                    description: "Setting up CI/CD pipelines and real-time monitoring to ensure 99.9% uptime.",
                },
            ],
            features: [
                "Microservices or Monolithic Architecture Support",
                "Real-time Data Streaming & Processing",
                "Advanced Caching Strategies (Redis)",
                "Third-party Service Integrations (Payment, Mail, Auth)",
                "Comprehensive API Documentation",
            ],
            techStack: [
                "Node.js",
                "Express",
                "Python",
                "PostgreSQL",
                "MongoDB",
                "Redis",
                "Docker",
                "AWS/Vercel",
            ],
            faq: [{
                    question: "Can you integrate with my existing database?",
                    answer: "Yes, we have experience working with various legacy and modern databases.",
                },
                {
                    question: "Is your code documented?",
                    answer: "We provide full documentation for all APIs, making it easy for other developers to integrate.",
                },
            ],
        },
    ],
    projects: [{
            id: 1,
            title: "Quantum Shop",
            description: "A modern online store with live stock updates and a beautiful design.",
            techStack: ["Next.js", "Tailwind CSS", "Stripe", "MongoDB"],
            purpose: "E-Commerce",
            details: "Developed a full-featured online shop with dynamic product filtering and secure checkout.",
            thumbnail: "/images/project1.jpg",
        },
        {
            id: 2,
            title: "Skyline Real Estate",
            description: "A modern house listing site with easy map search and price details.",
            techStack: ["React", "Node.js", "Google Maps API", "PostgreSQL"],
            purpose: "Real Estate",
            details: "A platform for realtors to list properties and for buyers to find their dream homes.",
            thumbnail: "/images/project2.jpg",
        },
    ],
    blogs: [{
            id: 1,
            title: "The Future of Web Development with Next.js 15",
            summary: "Exploring the new features and improvements in the latest version of Next.js.",
            content: "Next.js 15 brings significant performance improvements and a more streamlined development experience...",
            date: "2024-03-01",
            author: "Alex Cameron",
        },
        {
            id: 2,
            title: "Creating Beautiful Designs with Tailwind",
            summary: "Tips and tricks for creating high-quality designs that people love.",
            content: "Tailwind CSS has revolutionized the way we style applications. By leveraging its configuration system...",
            date: "2024-02-15",
            author: "Alex Cameron",
        },
    ],
    messages: [], // For contact form submissions
};