export const portfolioData = {
    profile: {
        name: "Pir Ghulam Muhyo Din",
        company: "Muhyo Tech",
        role: "Founder & Lead Solution Architect",
        bio: "Bridging Technology & Innovation with world-class software solutions.",
        longDescription: "With over 3 years of deep-rooted expertise in the software industry, I founded Muhyo Tech to transform complex technical challenges into elegant, high-performance digital realities. Our approach balances aesthetic precision with architectural integrity, ensuring every project is not just built, but engineered for the future. From Peshawar to the world, we bring a passion for excellence and a commitment to delivering results that truly matter.",
        mission: "To engineer simple, powerful, and beautiful digital ecosystems that empower businesses to scale and excel.",
        values: [
            "Architectural Excellence",
            "Performance First",
            "User-Centric Innovation",
            "Scalable Solutions",
            "Transparent Collaboration",
        ],
        avatar: "https://res.cloudinary.com/dg5gwixf1/image/upload/v1772736622/ChatGPT_Image_Mar_5_2026_11_36_42_AM_auw4uw.png",
        email: "MuhyoTech@gmail.com",
        phone: "+92 322 4458481",
        location: "Chung, Lahore, Pakistan",
        workingHours: "Mon - Sat: 9:00 AM - 6:00 PM",
        socials: {
            github: "https://github.com",
            linkedin: "https://linkedin.com",
            twitter: "https://twitter.com",
            facebook: "https://facebook.com",
        },
    },
    skills: [
        { name: "React / Next.js", level: 95, category: "Frontend" },
        { name: "Tailwind CSS", level: 90, category: "Frontend" },
        { name: "Node.js / Express", level: 85, category: "Backend" },
        { name: "TypeScript", level: 88, category: "Languages" },
        { name: "MongoDB", level: 80, category: "Database" },
        { name: "PostgreSQL", level: 82, category: "Database" },
        { name: "Framer Motion", level: 85, category: "Animation" },
        { name: "GraphQL", level: 75, category: "API" },
    ],
    services: [{
            id: 1,
            slug: "web-development",
            title: "Performance-First Web Development",
            description: "We engineer high-performance, SEO-optimized digital experiences using cutting-edge technologies like Next.js and React. Our websites aren't just pretty—they're built to convert and scale.",
            problemSolved: "Converting casual visitors into loyal customers through lightning-fast load times and intuitive user journeys that drive business growth.",
            benefits: [
                "Blazing Fast Core Web Vitals",
                "Advanced SEO Architecture",
                "Mobile-First Responsive Design",
                "Scalable Cloud-Native Infrastructure",
            ],
            process: [{
                    title: "Strategy & Discovery",
                    description: "Deep dive into your business goals, target audience, and competition to map out a clear digital strategy.",
                },
                {
                    title: "Technical Architecture",
                    description: "Planning the stack, database schema, and API integrations for a robust, future-proof system.",
                },
                {
                    title: "Agile Development",
                    description: "Iterative building with clean, maintainable code and regular progress updates.",
                },
                {
                    title: "Testing & Launch",
                    description: "Rigorous performance, security, and cross-browser testing before the final deployment.",
                },
            ],
            features: [
                "Server-Side Rendering (SSR) & Static Site Generation (SSG)",
                "Custom CMS Integration (Sanity, Contentful, or Strapi)",
                "E-commerce & Dynamic Payment Gateways",
                "Real-time Data & WebSockets Support",
                "Progressive Web App (PWA) Capabilities",
            ],
            techStack: [
                "React",
                "Next.js",
                "TypeScript",
                "Node.js",
                "Tailwind CSS",
                "MongoDB/PostgreSQL",
                "Framer Motion",
            ],
            banner: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=2072&auto=format&fit=crop",
            faq: [{
                    question: "How long does a typical project take?",
                    answer: "A standard web project usually takes 4-8 weeks depending on complexity.",
                },
                {
                    question: "Do you provide post-launch support?",
                    answer: "Yes, we offer monthly maintenance and support packages to keep your site updated and secure.",
                },
            ],
        },
        {
            id: 2,
            slug: "ui-ux-design",
            title: "User-Centric UI/UX Design",
            description: "Transforming complex requirements into simple, elegant, and intuitive user interfaces. We focus on strategic design that aligns with user behavior and business objectives.",
            problemSolved: "Eliminating user frustration and high bounce rates by creating seamless, engaging experiences that keep users coming back.",
            benefits: [
                "Intuitive User Workflows",
                "Consistent Design Systems",
                "Accessible & Inclusive Design",
                "High-Fidelity Prototyping",
            ],
            process: [{
                    title: "User Research",
                    description: "Understanding user personas, pain points, and behavioral patterns through data and interviews.",
                },
                {
                    title: "Wireframing",
                    description: "Creating low-fidelity blueprints to establish layout and information hierarchy.",
                },
                {
                    title: "Visual Design",
                    description: "Crafting beautiful, brand-aligned interfaces with a focus on typography and color theory.",
                },
                {
                    title: "Interaction Design",
                    description: "Adding motion and micro-interactions to breathe life into the final design.",
                },
            ],
            features: [
                "Custom Vector Illustrations & Icons",
                "Interactive High-Fidelity Prototypes",
                "Comprehensive Responsive Design Systems",
                "A/B Testing & Usability Research",
                "Dark Mode & Multi-Theme Support",
            ],
            techStack: [
                "Figma",
                "Adobe Creative Suite",
                "Framer",
                "Spline (3D)",
                "Principle",
            ],
            banner: "https://res.cloudinary.com/dg5gwixf1/image/upload/v1772738795/ChatGPT_Image_Mar_5_2026_12_26_08_PM_hdvfoz.png",
            faq: [{
                    question: "Can you redesign my existing website?",
                    answer: "Absolutely! We specialize in revamping outdated interfaces to modern, high-converting designs.",
                },
                {
                    question: "Do you provide the design files?",
                    answer: "Yes, you will receive full access to all design assets, including Figma files and exported assets.",
                },
            ],
        },
        {
            id: 3,
            slug: "api-development",
            title: "Scalable API & Backend Systems",
            description: "Architecting the invisible engine that powers your business. We build secure, robust, and lightning-fast APIs that handle complex logic and large data volumes with ease.",
            problemSolved: "Streamlining operations and data management through automated, reliable backend systems that eliminate manual errors.",
            benefits: [
                "Military-Grade Security",
                "High Availability Arch",
                "RESTful & GraphQL Support",
                "Easy 3rd-Party Integrations",
            ],
            process: [{
                    title: "Data Modeling",
                    description: "Designing efficient database schemas and relationships to optimize data retrieval.",
                },
                {
                    title: "API Design",
                    description: "Defining clean, documented endpoints using industry standards like OpenAPI/Swagger.",
                },
                {
                    title: "Security Implementation",
                    description: "Integrating JWT, OAuth, and advanced encryption to protect your sensitive data.",
                },
                {
                    title: "Deployment & Monitoring",
                    description: "Setting up CI/CD pipelines and real-time monitoring to ensure 99.9% uptime.",
                },
            ],
            features: [
                "Microservices or Monolithic Architecture Support",
                "Real-time Data Streaming & Processing",
                "Advanced Caching Strategies (Redis)",
                "Third-party Service Integrations (Payment, Mail, Auth)",
                "Comprehensive API Documentation",
            ],
            techStack: [
                "Node.js",
                "Express",
                "Python",
                "PostgreSQL",
                "MongoDB",
                "Redis",
                "Docker",
                "AWS/Vercel",
            ],
            banner: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop",
            faq: [{
                    question: "Can you integrate with my existing database?",
                    answer: "Yes, we have experience working with various legacy and modern databases.",
                },
                {
                    question: "Is your code documented?",
                    answer: "We provide full documentation for all APIs, making it easy for other developers to integrate.",
                },
            ],
        },
        {
            id: 4,
            slug: "mobile-app-development",
            title: "Cross-Platform Mobile Solutions",
            description: "Building high-performance, native-quality mobile applications for iOS and Android using modern frameworks. We focus on seamless performance and user engagement.",
            problemSolved: "Bridging the gap between your brand and users on the go through intuitive, feature-rich mobile experiences.",
            benefits: [
                "Single Codebase for iOS & Android",
                "Offline-First Functionality",
                "High-Performance Animations",
                "App Store Optimization (ASO)",
            ],
            process: [{
                    title: "Mobile Strategy",
                    description: "Defining user personas and mapping out the mobile-first customer journey.",
                },
                {
                    title: "Prototyping",
                    description: "Creating interactive mobile mockups to test usability and flow.",
                },
                {
                    title: "Development",
                    description: "Building with React Native or Flutter for efficient code sharing.",
                },
                {
                    title: "App Store Launch",
                    description: "Navigating the complexities of Google Play and Apple App Store submissions.",
                },
            ],
            features: [
                "Push Notifications & In-App Messaging",
                "Biometric Authentication (FaceID/TouchID)",
                "Geolocation & Mapping Services",
                "Offline Data Synchronization",
                "Native Module Integration",
            ],
            techStack: [
                "React Native",
                "Flutter",
                "Expo",
                "Firebase",
                "GraphQL",
                "Redux/Zustand",
            ],
            banner: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2070&auto=format&fit=crop",
            faq: [{
                    question: "Do you build for both iOS and Android?",
                    answer: "Yes, we use cross-platform technologies to build for both systems simultaneously, saving time and cost.",
                },
                {
                    question: "Can you help with app store publishing?",
                    answer: "Absolutely! We handle the entire submission process until your app is live and available for download.",
                },
            ],
        },
        {
            id: 5,
            slug: "cloud-devops",
            title: "Cloud Infrastructure & DevOps",
            description: "Optimizing your development lifecycle with automated CI/CD pipelines and scalable cloud architecture. We ensure your application is always available and secure.",
            problemSolved: "Eliminating deployment bottlenecks and server downtime through robust automation and intelligent scaling.",
            benefits: [
                "99.9% Uptime Guarantee",
                "Automated Security Patches",
                "Reduced Operational Costs",
                "Faster Release Cycles",
            ],
            process: [{
                    title: "Audit & Analysis",
                    description: "Evaluating your current infrastructure for bottlenecks and security vulnerabilities.",
                },
                {
                    title: "Automation Setup",
                    description: "Implementing CI/CD pipelines for seamless, low-risk deployments.",
                },
                {
                    title: "Cloud Migration",
                    description: "Moving your legacy systems to scalable, modern cloud providers like AWS or Azure.",
                },
                {
                    title: "Monitoring 24/7",
                    description: "Setting up real-time alerts and log management to prevent issues before they happen.",
                },
            ],
            features: [
                "Infrastructure as Code (Terraform/CloudFormation)",
                "Containerization with Docker & Kubernetes",
                "Automated Disaster Recovery & Backups",
                "Serverless Architecture Implementation",
                "Security & Compliance Hardening",
            ],
            techStack: [
                "AWS",
                "Azure",
                "Docker",
                "Kubernetes",
                "GitHub Actions",
                "Terraform",
                "Prometheus/Grafana",
            ],
            banner: "https://res.cloudinary.com/dg5gwixf1/image/upload/v1772738946/ChatGPT_Image_Mar_5_2026_12_28_47_PM_mrbwr1.png",
            faq: [{
                    question: "Which cloud provider do you recommend?",
                    answer: "We recommend AWS for its comprehensive toolset, but we also support Azure and Google Cloud based on your needs.",
                },
                {
                    question: "How do you ensure data security?",
                    answer: "We implement industry-standard encryption, VPCs, and regular security audits to keep your data safe.",
                },
            ],
        },
        {
            id: 6,
            slug: "seo-digital-growth",
            title: "SEO & Digital Growth Strategy",
            description: "Driving organic traffic and increasing visibility through data-driven SEO strategies and content optimization. We help you rank higher and reach your target audience.",
            problemSolved: "Solving low visibility and stagnant growth by positioning your brand where your customers are looking.",
            benefits: [
                "Higher Search Engine Rankings",
                "Increased Organic Traffic",
                "Data-Backed Growth Strategy",
                "Content Performance Tracking",
            ],
            process: [{
                    title: "Keyword Research",
                    description: "Identifying the terms your customers are searching for most.",
                },
                {
                    title: "Technical SEO",
                    description: "Optimizing site speed, schema markup, and crawlability for search engines.",
                },
                {
                    title: "Content Strategy",
                    description: "Creating a roadmap for valuable content that builds authority and trust.",
                },
                {
                    title: "Analytics & Reporting",
                    description: "Regularly reviewing performance metrics and adjusting strategies for maximum ROI.",
                },
            ],
            features: [
                "Comprehensive SEO Site Audits",
                "Competitor Link Building Analysis",
                "Local SEO & Google Business Profile Optimization",
                "Conversion Rate Optimization (CRO)",
                "Performance Data Visualization (Looker Studio)",
            ],
            techStack: [
                "Google Analytics 4",
                "Search Console",
                "Ahrefs",
                "SEMrush",
                "Screaming Frog",
                "Hotjar",
            ],
            banner: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop",
            faq: [{
                    question: "How long until I see results from SEO?",
                    answer: "SEO is a long-term strategy; typically, you'll see significant growth within 3-6 months.",
                },
                {
                    question: "Do you guarantee a #1 ranking?",
                    answer: "No ethical SEO can guarantee a #1 spot, but we guarantee improved visibility and high-quality traffic.",
                },
            ],
        },
    ],
    projects: [{
            id: 1,
            title: "Quantum Shop",
            description: "A high-performance e-commerce ecosystem featuring real-time inventory sync, Stripe integration, and an AI-driven recommendation engine.",
            techStack: ["Next.js", "Tailwind CSS", "Stripe", "MongoDB", "OpenAI"],
            purpose: "E-Commerce",
            category: "Web",
            details: "Built for a high-growth fashion brand, this platform reduced page load times by 40% and increased checkout conversion rates by 25% using edge caching and optimized image delivery.",
            thumbnail: "https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&q=80&w=1200",
            links: {
                live: "https://example.com",
                github: "https://github.com",
            },
            role: "Full-Stack Developer",
            impact: "2.5M+ Annual Revenue Processed",
        },
        {
            id: 2,
            title: "Skyline Real Estate",
            description: "A premium property discovery platform with integrated Google Maps API, virtual tour support, and a robust brokerage management system.",
            techStack: ["React", "Node.js", "PostgreSQL", "Google Maps", "Socket.io"],
            purpose: "Real Estate",
            category: "Web",
            details: "A comprehensive solution for property management that supports real-time chat between buyers and realtors, automated valuation models, and dynamic PDF report generation.",
            thumbnail: "https://images.unsplash.com/photo-1460317442991-0ec239f636a7?auto=format&fit=crop&q=80&w=1200",
            links: {
                live: "https://example.com",
                github: "https://github.com",
            },
            role: "Lead Architect",
            impact: "Used by 50+ Global Agencies",
        },
        {
            id: 3,
            title: "Aura AI Analytics",
            description: "An enterprise-level predictive analytics dashboard that uses machine learning to forecast market trends and user behavior patterns.",
            techStack: ["Python", "TensorFlow", "React", "D3.js", "AWS"],
            purpose: "AI & Data",
            category: "AI",
            details: "Developed a proprietary neural network model to process millions of data points daily, providing actionable insights for Fortune 500 financial firms with 94% accuracy.",
            thumbnail: "https://images.unsplash.com/photo-1551288049-bbda64626744?auto=format&fit=crop&q=80&w=1200",
            links: {
                live: "https://example.com",
                github: "https://github.com",
            },
            role: "Data Scientist & Frontend Engineer",
            impact: "Optimized Ad-Spend by 35%",
        },
        {
            id: 4,
            title: "Nexis Web 3.0 Portal",
            description: "A decentralized identity management platform using Ethereum smart contracts for secure, passwordless authentication across digital ecosystems.",
            techStack: ["Solidity", "Web3.js", "Next.js", "IPFS", "Hardhat"],
            purpose: "Blockchain",
            category: "Web3",
            details: "Revolutionized user login experiences by removing traditional databases, replacing them with immutable on-chain verification and decentralized storage for user metadata.",
            thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=1200",
            links: {
                live: "https://example.com",
                github: "https://github.com",
            },
            role: "Blockchain Developer",
            impact: "Zero Security Vulnerabilities Logged",
        },
        {
            id: 5,
            title: "Titan CRM System",
            description: "A custom-built relationship management tool designed for manufacturing giants to track supply chain logistics and client satisfaction metrics.",
            techStack: ["Vue.js", "Go", "Elasticsearch", "Docker", "Redis"],
            purpose: "SaaS",
            category: "Corporate",
            details: "Streamlined communication across 12 international departments, integrating with legacy ERP systems and providing real-time data synchronization across all devices.",
            thumbnail: "https://images.unsplash.com/photo-1454165833767-131ef24896c3?auto=format&fit=crop&q=80&w=1200",
            links: {
                live: "https://example.com",
                github: "https://github.com",
            },
            role: "Backend Lead",
            impact: "Saved 500+ Weekly Man-Hours",
        },
        {
            id: 6,
            title: "Zenith Mobile App",
            description: "A mental health and meditation application featuring biometric tracking, spatial audio sessions, and personalized progress visualization.",
            techStack: ["React Native", "Firebase", "Zustand", "Expo", "Reanimated"],
            purpose: "Health Tech",
            category: "Mobile",
            details: "Crafted a soothing, high-performance mobile experience with fluid 60FPS animations and offline capabilities to ensure users can access wellness tools anywhere.",
            thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=1200",
            links: {
                live: "https://example.com",
                github: "https://github.com",
            },
            role: "Mobile App Lead",
            impact: "4.8 Star App Store Rating",
        },
    ],
    blogs: [{
            id: 1,
            title: "The Future of Web Development with Next.js 15",
            summary: "Exploring the new features and improvements in the latest version of Next.js.",
            content: "Next.js 15 brings significant performance improvements and a more streamlined development experience...",
            date: "2024-03-01",
            author: "Alex Cameron",
        },
        {
            id: 2,
            title: "Creating Beautiful Designs with Tailwind",
            summary: "Tips and tricks for creating high-quality designs that people love.",
            content: "Tailwind CSS has revolutionized the way we style applications. By leveraging its configuration system...",
            date: "2024-02-15",
            author: "Alex Cameron",
        },
    ],
    messages: [], // For contact form submissions
};